# Generated by Django 5.0.1 on 2024-01-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cws', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cws',
            name='cws_code',
            field=models.TextField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='cws',
            name='cws_name',
            field=models.TextField(default=None, max_length=20),
        ),
    ]
