# Generated by Django 5.0.1 on 2024-01-17 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cws_name', models.TextField(max_length=255)),
                ('purchase_date', models.DateField()),
                ('farmer_code', models.TextField(max_length=255)),
                ('farmer_name', models.TextField(max_length=255)),
                ('season', models.IntegerField()),
                ('cherry_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('has_card', models.IntegerField()),
                ('cherry_grade', models.TextField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paper_grn_no', models.CharField(max_length=20)),
                ('transport', models.DecimalField(decimal_places=2, max_digits=10)),
                ('batch_no', models.TextField(max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
    ]
