# Generated by Django 5.0.1 on 2024-01-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0002_remove_farmer_email_farmer_national_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='cws',
            field=models.TextField(default=None, max_length=255),
        ),
    ]
